import { ComponentType } from 'react';
import {
  ArrowsLeftRightIcon,
  BarbellIcon,
  BowlFoodIcon,
  BowlSteamIcon,
  BreadIcon,
  CakeIcon,
  CalendarBlankIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CarrotIcon,
  ChartLineUpIcon,
  CheckCircleIcon,
  CheckIcon,
  CoffeeIcon,
  DropHalfBottomIcon,
  DropIcon,
  EggIcon,
  FishIcon,
  FlagIcon,
  FlameIcon,
  FootprintsIcon,
  ForkKnifeIcon,
  GaugeIcon,
  GearSixIcon,
  GenderFemaleIcon,
  GenderMaleIcon,
  HamburgerIcon,
  HeartIcon,
  HouseIcon,
  IceCreamIcon,
  ImageIcon,
  InfoIcon,
  LeafIcon,
  LightningIcon,
  LockIcon,
  MagnifyingGlassIcon,
  PencilSimpleIcon,
  PintGlassIcon,
  PizzaIcon,
  PlusCircleIcon,
  PlusIcon,
  RulerIcon,
  ScalesIcon,
  ScanIcon,
  SignOutIcon,
  SmileyIcon,
  SparkleIcon,
  SunIcon,
  TargetIcon,
  TrashIcon,
  TrendDownIcon,
  TrendUpIcon,
  UserIcon,
  XIcon,
  type IconProps,
  type IconWeight,
} from 'phosphor-react-native';

import { theme } from '@/theme';

type PhosphorIcon = ComponentType<IconProps>;

// Curated semantic icon set → Phosphor glyphs. Call sites reference the meaning
// (`calories`, `scan`, `chevron`), never the underlying font, so the whole app
// speaks one icon language and swapping a glyph is a one-line change here.
export const ICONS = {
  home: HouseIcon,
  homeOutline: HouseIcon,
  scan: ScanIcon,
  scanOutline: ScanIcon,
  camera: CameraIcon,
  image: ImageIcon,
  search: MagnifyingGlassIcon,
  calendar: CalendarBlankIcon,
  calendarOutline: CalendarBlankIcon,
  chart: ChartLineUpIcon,
  chartOutline: ChartLineUpIcon,
  person: UserIcon,
  personOutline: UserIcon,
  plus: PlusIcon,
  trash: TrashIcon,
  chevron: CaretRightIcon,
  chevronBack: CaretLeftIcon,
  chevronDown: CaretDownIcon,
  flame: FlameIcon,
  flameFilled: FlameIcon,
  close: XIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  restaurant: ForkKnifeIcon,
  fastFood: HamburgerIcon,
  pizza: PizzaIcon,
  cafe: CoffeeIcon,
  drink: PintGlassIcon,
  dessert: IceCreamIcon,
  fish: FishIcon,
  egg: EggIcon,
  bowl: BowlSteamIcon,
  cereal: BowlFoodIcon,
  sunny: SunIcon,
  sparkles: SparkleIcon,
  flash: LightningIcon,
  nutrition: CarrotIcon,
  muscle: BarbellIcon,
  leaf: LeafIcon,
  loseWeight: TrendDownIcon,
  gainWeight: TrendUpIcon,
  maintain: ArrowsLeftRightIcon,
  calories: FlameIcon,
  protein: BarbellIcon,
  carbs: BreadIcon,
  fat: DropIcon,
  fibre: LeafIcon,
  water: DropHalfBottomIcon,
  weight: ScalesIcon,
  height: RulerIcon,
  age: CakeIcon,
  flag: FlagIcon,
  target: TargetIcon,
  steps: FootprintsIcon,
  relaxed: SmileyIcon,
  balanced: GaugeIcon,
  strict: TargetIcon,
  female: GenderFemaleIcon,
  male: GenderMaleIcon,
  heart: HeartIcon,
  heartOutline: HeartIcon,
  settings: GearSixIcon,
  logout: SignOutIcon,
  edit: PencilSimpleIcon,
  add: PlusCircleIcon,
  swap: ArrowsLeftRightIcon,
  info: InfoIcon,
  lock: LockIcon,
  lockOutline: LockIcon,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

type Props = { name: IconName; size?: number; color?: string; weight?: IconWeight };

/**
 * The app's single icon primitive. `weight` defaults to `regular` for crisp
 * controls (tab bar, chevrons, close); pass `weight="duotone"` in the tinted
 * chips, gauges and food tiles for FitBite's two-tone brand look — the duotone
 * fill mirrors the icon colour, so it reads as a lighter wash of the same tint.
 */
export function Icon({ name, size = 22, color = theme.color.textPrimary, weight = 'regular' }: Props) {
  const Glyph = ICONS[name];
  return <Glyph size={size} color={color} weight={weight} duotoneColor={color} duotoneOpacity={0.22} />;
}
